dist: trusty

sudo: required

language: ruby

cache: bundler

env:
  - BOT_USERNAME=kite-bot BOT_NAME="Kite Bot" BOT_EMAIL=kite-bot@heliostech.fr REPOSITORY_SLUG=rubykube/peatio-trading-ui

services:
  - docker

# Execute all of the commands which need to be executed before installing dependencies.
before_install:
  - gem install bundler

# Execute all of the commands which should install application dependencies.
install:
  - bundle install --deployment --without production development --jobs=$(nproc) --retry=3

# Execute all of the commands which need to be executed before running actual tests.
before_script:
  - ./bin/init_config

# Execute all of the commands which should make the build pass or fail.
script:
  docker build --tag peatio-trading-ui .

# Execute all of the commands which need to be executed after the build passed.
after_success: ruby ci/bump.rb

# Execute all of the commands which need to be executed after the build failed.
after_failure:

notifications:
  slack:
    rooms:
      - secure: tR80SJaiYgXX5MzArMGN+J2WM/9NpiIQ8kXqEPhXxr3H82L7w+JAzG9nz1iIgC4+WAhcAC0GPzMR9T+sJEqh5g7aOtSdubI2Edt6nxJULDtB1QicaLZYATesJ7auBDwmiHbxaeLAmh/qPzK2TETmYX4/xktMkApaZgvvruDHUHpffKN+fMbhuK+sDwcv9RCotjbLs+flCO3aSwAM8cyEV52/UncKBj1gEHHY+WVBDTfKO9kLSBMhZQrTLiYBi59GNthXr4Xi7wp0hQflN7KeRw0zNB4BpxylyfW05/loK7+CAecxDzS3dXkqgOT56fUu7FCdUXxTu/cPHr7mXdOxRRzpX80QC6+/vr+Kw58omXHuJG97g2j8O9LDJS3zfOBCgiIbw2e0sCtnamK5aNvpCNuPAoJ7w9MUGnkOYmR73zpGqrOeT8pbJu5QEcz5InzSjV/ym7ETBIrJSf1DZvxd52OPqDa8pVOHtg3MR43pO9ZW+E0YCea/UxoqDnPZb1yC3yJuVNeO1951Q0Tgr/oDar7yWTQMPuGyQ7jnrhl83CVSvYbGCNzA9psxAy2UjdwZf1WmiZofoO63XRIWdEmVHXnxZFEEsjB4r6R9yZRoqa909Z1+b1zFd+uJdQ1zQzsDgFxAH1FFSaEEiFtV9G0Xa8AFOgB7UYtCZsCXFCVid6Y=
    on_success: change
